# Optional: List funding links for the GitHub "Sponsor" button.
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [vvk147]
open_collective: vvk-147
# Uncomment and set your username when you create a page:
# ko_fi: vvk147
# custom: ['https://buymeacoffee.com/vvk147']
